### ISSUE TITLE
Just any bit of wind and AP goes insane

### ISSUE THREAD

**Issue by BlynTwitch** [nicolas377/GeoFS-Autoland#13]
This had me pissed bc I was in the middle of the ocean and my plane starts going left and right and it just stalled in the ocean and I wasted 4 hours on a failure

**Comment by nicolas377** [comment]
This is generally an ap++ thing overall, so I would say with no guarantees that this wont be fixed for a while, but it will still be on the table of things to do. I won't assign it to a update as it is relatively low priority for now, but it'll still be worked on

**Comment by nicolas377** [comment]
Unfortunately, this issue cannot be resolved, and thus will stay closed until a possible solution is found.
