### ISSUE TITLE
So

### ISSUE THREAD

**Issue by Alpha780** [nicolas377/GeoFS-Autoland#15]
Can you fix the elevators that just flip in and out with AP++. Like the A380?

**Comment by nicolas377** [comment]
This is mostly a default ap issue so it wont be high priority, but it wont be left out in the future.

**Comment by nicolas377** [comment]
Generally, this would require a complete overhaul of ap++, which I don't have the patience for. It's possible that in the very far future that this could happen, but this issue will be closed with no definite chance of being reopened.
