### ISSUE TITLE
Autoland source code instead of minified code

### ISSUE THREAD

**Issue by PH-KDX** [nicolas377/GeoFS-Autoland#18]
Instead of basing Autoland on the minified version of the AP++ and FMC, perhaps it could be based on the source code.
Having the non-minified source code of Autoland would make the code more readable, which is easier both for debugging and for contributing.

**Comment by captainFoxtrot** [comment]
"minified version" being the really unreadable one that you see in the original from [here](https://github.com/Qantas94Heavy/autopilot-pp/releases/tag/v0.11.2) and in this repo at [code/ap++.js](https://github.com/nicolas377/GeoFS-Autoland/blob/master/code/AP%2B%2B.js); "non-minified" is what you see in the [source](https://github.com/Qantas94Heavy/autopilot-pp/tree/v0.11.2/source) directory in the original AP++ repo.

**Comment by nicolas377** [comment]
Thanks for the suggestion! I already have the source code installed on this machine, but I'm not completely sure how I'd minify the code. I've already reached out to Q94Heavy (though its unlikely he'll get back to me), but if you have any recommendations, let me know.

**Comment by nicolas377** [comment]
My main problem is how I'd merge the files into the userscript. It's possible I'd have to do it manually, but I'll see.

**Comment by nicolas377** [comment]
AP++ and FMC generally won't be touched from here on out, except for using a while statement and some json messages in the extension. So, I'll close this for now.
