### ISSUE TITLE
 Landing problem

### ISSUE THREAD

**Issue by FuriousCobra** [nicolas377/GeoFS-Autoland#19]
So the beginning of the flight is smooth but, when the I am a few hundred ft. from the runway the VNAV bugs out and it doesn't land the plane. It hovers above the runway and I tried setting altitude 150 ft below the original runway altitude but then it just dive bombs when it gets just above the runway.

**Comment by nicolas377** [comment]
Thanks for your report! There is a document already [here](https://docs.google.com/document/d/1F4ybxKhG5QYbvifkP2A9epeX30FT6SfWLM5l7KKaSts/edit) that you can use to make the route not slam into the ground. I'm working on functionality for FMC to be able to accept altitudes in ones instead of tens to make the landing more precise.

**Comment by FuriousCobra** [comment]
I looked at the document, how do you identify the other end of the runway's coordinates?

**Comment by FuriousCobra** [comment]
So I figured it out and this happened: https://www.youtube.com/watch?v=fry728NcPf8
(It is pretty glichy, not sure why)

**Comment by nicolas377** [comment]
At the moment, the video is private. Try making it unlisted so I can see

**Comment by FuriousCobra** [comment]
Here now try: https://www.youtube.com/watch?v=fry728NcPf8&feature=youtu.be

**Comment by nicolas377** [comment]
Could you send the route used, and the version of autoland you were running?

**Comment by FuriousCobra** [comment]
AP++, Kona-Kahului      https://wkevin.com/geofs/flight-1103/

**Comment by FuriousCobra** [comment]
Autoland and Autopilot version 11.2

**Comment by nicolas377** [comment]
That route is not an autoland route.

**Comment by FuriousCobra** [comment]
Where are the auto land routes

**Comment by FuriousCobra** [comment]
Where are the auto land routes

**Comment by nicolas377** [comment]
There is a video tutorial, and the routes.html file has many

**Comment by FuriousCobra** [comment]
Ok,I think I figured it out! Thanks so much.
