### ISSUE TITLE
VNAV not descending

### ISSUE THREAD

**Issue by iiRevzz** [nicolas377/GeoFS-Autoland#20]
So, when you get to the waypoint where it should be descending, it doesn't register the altitude that you put in for the specific waypoint, but when you change the VNAV to an altitude higher than what you had set previously, like if you set it to 10,000, and put it to 10,001 it would register the waypoint's altitude and would work. Setting the VNAV to 0 on descent didn't fix it.

**Comment by nicolas377** [comment]
I'm pretty sure this is a flaw with FMC itself. The optimal end-user solution would be to set the T/D distance as needed.
