### ISSUE TITLE
Pre-made Autoland Routes

### ISSUE THREAD

**Issue by FuriousCobra** [nicolas377/GeoFS-Autoland#21]
Are there any full routes from takeoff to landing?

**Comment by nicolas377** [comment]
Not at the moment, though it's possible such routes could be added in the future.

**Comment by nicolas377** [comment]
If you have some, put them here and I might add them.

**Comment by extremepro999** [comment]
Yeah full route would make this plugin a hittttt

**Comment by nicolas377** [comment]
I'll probably use an opt-in feature that sends all routes to a database. That can be used for an eventual extension that can fill in all fields.
