### ISSUE TITLE
Flippidy Flaps and gears

### ISSUE THREAD

**Issue by BigBoiFlights-Ryan** [nicolas377/GeoFS-Autoland#5]
i think to also make it as hands free as possible it automatically puts down the gear and pulls up flaps on descent?

**Comment by nicolas377** [comment]
This will most likely occur at v 0.1-0.

**Comment by BigBoiFlights-Ryan** [comment]
kk

**Comment by nicolas377** [comment]
Update: this will be added in 0.2-0

**Comment by nicolas377** [comment]
Make that 0.3-0 for gear, no promises on the flaps.

**Comment by nicolas377** [comment]
Gear, flaps, and sound package will be in the chrome extension for 0.3-0
